ALTER TABLE subject ALTER COLUMN birthday DATE NOT NULL;
ALTER TABLE mark ADD CONSTRAINT CHK_Mark CHECK(mark >= 1 AND mark <= 10);
ALTER TABLE mark ALTER COLUMN student_id BIGINT NOT NULL;
ALTER TABLE mark ALTER COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE student ADD CONSTRAINT CHK_Grade CHECK(grade >= 1 AND grade <= 5);
ALTER TABLE paymenttype ADD UNIQUE(name);
ALTER TABLE payment ALTER COLUMN type_id BIGINT NOT NULL;
ALTER TABLE payment ALTER COLUMN amount decimal NOT NULL;
ALTER TABLE payment ALTER COLUMN payment_date DateTime NOT NULL;

