ALTER TABLE subject MODIFY COLUMN birthday DATE NOT NULL;
ALTER TABLE mark ADD CHECK(mark >= 1 AND mark <= 10);
ALTER TABLE mark MODIFY COLUMN student_id BIGINT NOT NULL;
ALTER TABLE mark MODIFY COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE student ADD CHECK(grade >= 1 AND grade <= 5);
ALTER TABLE paymenttype MODIFY COLUMN name VARCHAR(45) UNIQUE;
ALTER TABLE payment MODIFY COLUMN type_id BIGINT NOT NULL;
ALTER TABLE payment MODIFY COLUMN amount decimal NOT NULL;
ALTER TABLE payment MODIFY COLUMN payment_date DateTime NOT NULL;

